### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by i10416** [i10416/dbc4s#11]
- [ ] advanced spark options(e.g. env, cluster profile)
- [ ] list all jobs
- [ ] api/scala 3 support
- [ ] delete job(s)
- [x] upload jvm library
  - [ ] install/uninstall uploaded lib to clusters
  - https://docs.databricks.com/dev-tools/api/latest/libraries.html#install
  - can I swap present lib with new one if old lib is installed in cluster?
- [ ] update an existing job
- [ ] parameter to configure spark version
